/*
Copyright (C) 2025,2026 Rodrigo Jose Hernandez Cordoba

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
#ifndef AEONGUI_DOM_EVENT_H
#define AEONGUI_DOM_EVENT_H
#include <cstdint>
#include <optional>
#include <vector>
#include <chrono>
#include "aeongui/Platform.hpp"
#include "DOMString.hpp"
#include "EventTarget.hpp"

namespace AeonGUI
{
    namespace DOM
    {
        /** @brief High-resolution timestamp type for events. */
        using DOMHighResTimeStamp = std::chrono::time_point<std::chrono::high_resolution_clock>;
        /** @brief Initialization dictionary for Event construction. */
        struct EventInit
        {
            bool bubbles{false};    ///< Whether the event bubbles up the DOM tree.
            bool cancelable{false}; ///< Whether the event can be cancelled.
            bool composed{false};   ///< Whether the event crosses shadow DOM boundaries.
        };

        /** @brief Represents a DOM event.
         *
         *  Events are dispatched to EventTarget objects and carry
         *  information about the occurrence (type, target, phase, etc.).
         *  @see https://dom.spec.whatwg.org/#interface-event
         */
        class Event
        {
        public:
            /** @brief Construct an event of the given type.
             *  @param type The event type name.
             *  @param eventInitDict Optional initialization dictionary.
             */
            Event ( const DOMString& type, const std::optional<EventInit>& eventInitDict = {} );
            /** @brief Build the composed path for this event. */
            std::vector<EventTarget> composedPath() const;
            /** @brief Stop the event from propagating further. */
            void stopPropagation();
            /** @brief Stop the event from propagating and prevent other listeners on the same target. */
            void stopImmediatePropagation();
            /** @brief Cancel the event's default action, if cancelable. */
            void preventDefault();

            const uint16_t NONE{0};            ///< No phase.
            const uint16_t CAPTURING_PHASE{1}; ///< Capture phase.
            const uint16_t AT_TARGET{2};       ///< At-target phase.
            const uint16_t BUBBLING_PHASE{3};  ///< Bubble phase.

            /** @brief Get the event type. */
            constexpr const DOMString& type() const
            {
                return m_type;
            }
            /** @brief Get the target of the event. */
            constexpr const EventTarget* const target() const
            {
                return m_target;
            }
            /** @brief Get the current target during dispatch. */
            constexpr const EventTarget* const currentTarget() const
            {
                return m_currentTarget;
            }
            /** @brief Get the current event phase. */
            constexpr uint16_t eventPhase() const
            {
                return m_eventPhase;
            }
            /** @brief Check whether the event bubbles. */
            constexpr bool bubbles() const
            {
                return m_bubbles;
            }
            /** @brief Check whether the event is cancelable. */
            constexpr bool cancelable() const
            {
                return m_cancelable;
            }
            /** @brief Check whether the default action was prevented. */
            constexpr bool defaultPrevented() const
            {
                return m_defaultPrevented;
            }
            /** @brief Check whether the event is composed. */
            constexpr bool composed() const
            {
                return m_composed;
            }
            /** @brief Check whether the event was generated by the user agent. */
            constexpr bool isTrusted() const
            {
                return m_isTrusted;
            }
            /** @brief Get the event's creation timestamp. */
            constexpr const DOMHighResTimeStamp& timeStamp() const
            {
                return m_timeStamp;
            }

        private:
            DOMString m_type;
            EventTarget* m_target{};
            EventTarget* m_currentTarget{};
            uint16_t m_eventPhase{NONE};
            bool m_bubbles{};
            bool m_cancelable{};
            bool m_defaultPrevented{};
            bool m_composed{};
            bool m_isTrusted{};
            DOMHighResTimeStamp m_timeStamp{};
        };
    }
}
#endif
