static const char* fragment_shader =
    "#ifdef GL_ES\n"
    "#version 100\n"
    "precision mediump float;\n"
    "#else\n"
    "#version 140\n"
    "out vec4 frag_color;\n"
    "#endif\n"
    "\n"
    "uniform sampler2D screen_texture;\n"
    "in vec2 uvout;\n"
    "\n"
    "void main(void)\n"
    "{\n"
    "#ifdef GL_ES\n"
    "    gl_FragColor =\n"
    "#else\n"
    "    frag_color = \n"
    "#endif\n"
    "        texture2D(screen_texture,uvout);\n"
    "}\n"
    ;
