# Copyright 2015 AeonGames, Rodrigo Hernandez
# Licensed under the terms of the Apache 2.0 License.
include(FindLibXml2)
if(NOT LIBXML2_FOUND)
	#LIBXML2 Version 2.9.2 has a broken MSVC build system (missing configure.in from the distro)
	set(XML2_VERSION 2.9.1)
	if(NOT EXISTS "${CMAKE_SOURCE_DIR}/libxml2-${XML2_VERSION}.tar.gz")
		message(STATUS "libxml2 support requested but not found, please wait while the software package is downloaded...")
		set(ENV{http_proxy} "${HTTP_PROXY}")
		file(DOWNLOAD "ftp://xmlsoft.org/libxml2/libxml2-${XML2_VERSION}.tar.gz" "${CMAKE_SOURCE_DIR}/libxml2-${XML2_VERSION}.tar.gz" STATUS libxml2_dl_status LOG libxml2_dl_log SHOW_PROGRESS)
		if(NOT libxml2_dl_status MATCHES "0;")
			message("Download failed, did you set a proxy? ${libxml2_dl_status}")
		endif(NOT libxml2_dl_status MATCHES "0;")
		message(STATUS "Done downloading libxml2")
	endif(NOT EXISTS "${CMAKE_SOURCE_DIR}/libxml2-${XML2_VERSION}.tar.gz")
	if(NOT IS_DIRECTORY "${CMAKE_SOURCE_DIR}/libxml2-${XML2_VERSION}")
		message(STATUS "Extracting libxml2...")
		execute_process(COMMAND cmake -E tar xzvf libxml2-${XML2_VERSION}.tar.gz WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
	endif(NOT IS_DIRECTORY "${CMAKE_SOURCE_DIR}/libxml2-${XML2_VERSION}")
	set(LIBXML2_INCLUDE_DIR "${CMAKE_BINARY_DIR}/libxml2/include/libxml2")
	if(MSVC)
		string(REGEX REPLACE "/" "\\\\" WIN_CMAKE_BINARY_DIR ${CMAKE_BINARY_DIR})
		message(STATUS "Configuring libxml2...")
		execute_process(COMMAND cscript configure.js debug=yes iconv=no prefix=${WIN_CMAKE_BINARY_DIR}\\libxml2 WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}/libxml2-${XML2_VERSION}/win32")
		#set(LIBXML2_LIBRARIES "${CMAKE_BINARY_DIR}/libxml2/lib/libxml2.lib" CACHE STRING "LibXml2 Library" FORCE)
		set(LIBXML2_LIBRARIES "${CMAKE_BINARY_DIR}/libxml2/lib/libxml2.lib")
		add_custom_target(LibXml2 nmake install WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}/libxml2-${XML2_VERSION}/win32" COMMENT "Building LibXml2" VERBATIM)
	else(MSVC)
		set(LIBXML2_LIBRARIES "xml2" CACHE STRING "LibXml2 Library" FORCE)
	endif(MSVC)
endif(NOT LIBXML2_FOUND)
