# Copyright 2015 AeonGames, Rodrigo Hernandez
# Licensed under the terms of the Apache 2.0 License.

find_package(GIT)
find_package(Subversion)
find_package(PythonInterp)
set(ENV{http_proxy} "${HTTP_PROXY}")
if(GIT_FOUND)
	if(NOT IS_DIRECTORY "${CMAKE_SOURCE_DIR}/v8")
		message(STATUS "Git executable is at ${GIT_EXECUTABLE}")
		message(STATUS "Cloning v8 git repository, this may take some time depending on your network connection")
		EXECUTE_PROCESS(COMMAND ${GIT_EXECUTABLE} clone https://chromium.googlesource.com/v8/v8.git v8 WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}" RESULT_VARIABLE git_clone_v8_result OUTPUT_VARIABLE git_clone_v8_output ERROR_VARIABLE git_clone_v8_output)
		if(NOT git_clone_v8_result EQUAL 0)
			MESSAGE(FATAL_ERROR "Cloning v8 git repository failed, perhaps you need to set your proxy with git config --global http.proxy <proxy address:port>\n${git_clone_v8_result}: ${git_clone_v8_output}")
		endif(NOT git_clone_v8_result EQUAL 0)
		#EXECUTE_PROCESS(COMMAND ${CMAKE_MAKE_PROGRAM} dependencies WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}/v8")
	endif(NOT IS_DIRECTORY "${CMAKE_SOURCE_DIR}/v8")
endif(GIT_FOUND)

if(MSVC)
	if(NOT EXISTS "${CMAKE_SOURCE_DIR}/depot_tools.zip")
		message(STATUS "Please wait while downloading depot_tools...")		
		file(DOWNLOAD "https://src.chromium.org/svn/trunk/tools/depot_tools.zip" "${CMAKE_SOURCE_DIR}/depot_tools.zip" STATUS dl_status LOG dl_log SHOW_PROGRESS)
		if(NOT dl_status MATCHES "0;\"No error\"")
			file(REMOVE "${CMAKE_SOURCE_DIR}/depot_tools.zip")
			message(FATAL_ERROR "Download failed, did you set a proxy? STATUS: ${dl_status}")
		endif(NOT astyle_dl_status MATCHES "0;\"No error\"")
		message(STATUS "Done downloading Astyle binary")
	endif(NOT EXISTS "${CMAKE_SOURCE_DIR}/depot_tools.zip")
	# Extract depot_tools.
	if(NOT EXISTS "${CMAKE_SOURCE_DIR}/depot_tools/gclient")
		message(STATUS "Extracting depot_tools...")
		execute_process(COMMAND cmake -E tar xzvf depot_tools.zip WORKING_DIRECTORY ${CMAKE_SOURCE_DIR} ERROR_VARIABLE extract_result)
	endif()
	string(REGEX REPLACE "/" "\\\\" WIN_DEPOT_TOOLS_PATH "${CMAKE_SOURCE_DIR}/depot_tools")
	if(NOT "$ENV{PATH}" MATCHES "depot_tools")
		set(ENV{PATH} "$ENV{PATH};${WIN_DEPOT_TOOLS_PATH}")
	endif()
	message(STATUS "Running gclient...")
	execute_process(COMMAND gclient.bat WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}/depot_tools" OUTPUT_VARIABLE result ERROR_VARIABLE error)
	message(STATUS "Done.\nresult:\n${result}\n")
endif(MSVC)
