name: Build on Windows

on: [push, pull_request]

env:
    VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        compiler: [msvc]

    steps:
    - uses: actions/checkout@v2

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      if: matrix.compiler == 'msvc'

    - name: Install VCPKG Dependencies
      run: C:/vcpkg/vcpkg.exe install --binarysource="clear;x-gha,readwrite" --x-manifest-root=${{github.workspace}}
      if: matrix.compiler == 'msvc'

    - name: Configure CMake (Windows Visual Studio)
      run: cmake -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -B ${{github.workspace}}/build
      if: matrix.compiler == 'msvc'

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Run Tests
      run: ctest --test-dir ${{github.workspace}}/build
